services:
  redis:
    image: "redis"
  osm2svgapi:
    image: "osm2svgapi"
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
  wrk1:
    image: "osm2svg"
    depends_on: 
      - "redis"
  wrk2:
    image: "osm2svg"
    depends_on: 
      - "redis"
  wrk3:
    image: "osm2svg"
    depends_on: 
      - "redis"
  wrk4:
    image: "osm2svg"
    depends_on: 
      - "redis"
    
